[package]
name = "hearts-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
hearts-game = { path = "../game-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.1"
clap = { version = "4.5", features = ["derive"] }
chrono = "0.4"
